### ISSUE TITLE
When trying to run ansible-lint from current master, it crashes

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/ansible-lint#1151]
##### Summary
```
$ ansible-lint .
Traceback (most recent call last):
  File "/usr/bin/ansible-lint", line 33, in <module>
    sys.exit(load_entry_point('ansible-lint', 'console_scripts', 'ansible-lint')())
  File "/usr/bin/ansible-lint", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/path/to/ansible-lint/lib/ansiblelint/__main__.py", line 33, in <module>
    from ansiblelint.color import console, console_options, console_stderr, reconfigure, render_yaml
  File "/path/to/ansible-lint/lib/ansiblelint/color.py", line 24, in <module>
    console_stderr = Console(**console_options, stderr=True)
TypeError: __init__() got an unexpected keyword argument 'soft_wrap'
```

I have:
```
$ pip show rich
Name: rich
Version: 9.4.0
Summary: Render rich text, tables, progress bars, syntax highlighting, markdown and more to the terminal
Home-page: https://github.com/willmcgugan/rich
Author: Will McGugan
Author-email: willmcgugan@gmail.com
License: MIT
Location: /usr/lib/python3.9/site-packages
Requires: pygments, commonmark, colorama, typing-extensions
Required-by: ansible-lint
```

It looks to me this only works with https://github.com/willmcgugan/rich/pull/347 which will not get merged.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details
Installed from e7607a900809b12b4b5b3606570d875962d57110 (current master).

**Comment by felixfontein** [comment]
This problem was introduced in #1088 two days ago.

**Comment by ssbarnea** [comment]
@felixfontein Have you tried to run `pip check` first? I bet you have some outdated dependencies as rich already implemented this feature: https://github.com/willmcgugan/rich/blob/6b748283c2e0b12018965367c19d17d8077525af/rich/console.py#L429

I guess you are using editable install and you pull new version without running install again and ended with some outdated deps, likely rich itself.

**Comment by felixfontein** [comment]
@ssbarnea I noticed I have a "too old" version of rich, 9.4.0 (from December 12th) as opposed to the latest 9.5.1 (from December 9.5.1). This is still a problem with ansible-lint though, since I explicitly installed ansible-lint from git, and it did not ensure that a new enough rich version is installed. It simply requires rich, not rich >= 9.5.0 (what I would assume to be the correct dependency).
